name: Build and Deploy Truecaller for web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        working-directory: ./
        run: npm ci --legacy-peer-deps

      - name: Code Linting
        run: npm run lint

      - name: Build React app
        working-directory: ./
        run: npm run build

      # Copy index.html to 404.html
      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./dist
